export function getElements() {
  const byId = (...ids) => ids.map((id) => document.getElementById(id)).find(Boolean) || null;
  return {
    catalogue: byId('catalogueFlatView', 'catalogue'),
    catalogueBack: document.getElementById('catalogueBack'),
    catalogueDetail: byId('catalogueDetailView', 'catalogueDetail'),
    catalogueFilters: document.getElementById('catalogueFilters'),
    catalogueList: document.getElementById('catalogueListView'),
    categoryPills: document.getElementById('categoryPills'),
    catalogueForward: document.getElementById('catalogueForward'),
    catalogueHistory: document.getElementById('catalogueHistory'),
    catalogueHistoryPanel: document.getElementById('catalogueHistoryPanel'),
    catalogueHome: document.getElementById('catalogueHome'),
    catalogueSort: document.getElementById('catalogueSort'),
    activeLayers: document.getElementById('activeLayers'),
    catalogueView: document.getElementById('catalogueView'),
    catalogueStats: byId('filterStats', 'catalogueStats'),
    copyDiagnostics: document.getElementById('copyDiagnostics'),
    diagnostics: document.getElementById('diagnostics'),
    diagnosticsClearHistory: document.getElementById('diagnosticsClearHistory'),
    diagnosticsSeverity: document.getElementById('diagnosticsSeverity'),
    diagnosticsSort: document.getElementById('diagnosticsSort'),
    diagnosticsType: document.getElementById('diagnosticsType'),
    fallbackAlerts: document.getElementById('fallbackAlerts'),
    featureDetails: document.getElementById('featureDetails'),
    featureResults: document.getElementById('featureResults'),
    mapSearch: byId('searchInput', 'mapSearch'),
    mapSearchClear: byId('searchClear', 'mapSearchClear'),
    mapControlsClose: document.getElementById('mapControlsClose'),
    mapControlsToggle: document.getElementById('mapControlsToggle'),
    mapTools: document.getElementById('mapTools'),
    mobileMenuSupport: document.getElementById('mobileMenuSupport'),
    mobileMenuTheme: document.getElementById('mobileMenuTheme'),
    mobileMenu: document.getElementById('mobileMenu'),
    mobileMenuBtn: document.getElementById('mobileMenuBtn'),
    mobileSupportBtn: document.getElementById('mobileSupportBtn'),
    preferencesDeviceDefaults: document.getElementById('preferencesDeviceDefaults'),
    preferencesApplyProfile: document.getElementById('preferencesApplyProfile'),
    preferencesExport: document.getElementById('preferencesExport'),
    preferencesImport: document.getElementById('preferencesImport'),
    preferencesPayload: document.getElementById('preferencesPayload'),
    preferencesProfileName: document.getElementById('preferencesProfileName'),
    preferencesProfileSelect: document.getElementById('preferencesProfileSelect'),
    preferencesReset: document.getElementById('preferencesReset'),
    preferencesResetCatalogue: document.getElementById('preferencesResetCatalogue'),
    preferencesResetLayers: document.getElementById('preferencesResetLayers'),
    preferencesResetShell: document.getElementById('preferencesResetShell'),
    preferencesSaveProfile: document.getElementById('preferencesSaveProfile'),
    preferencesStatus: document.getElementById('preferencesStatus'),
    providerPills: document.getElementById('providerPills'),
    screenReaderStatus: document.getElementById('screenReaderStatus'),
    sourceFilter: document.getElementById('sourceFilter'),
    sourcePanel: document.getElementById('sourcePanel'),
    sidebar: document.getElementById('testSidebar'),
    sidebarToggle: document.getElementById('sidebarToggle'),
    supportBtn: document.getElementById('supportBtn'),
    supportModal: document.getElementById('supportModal'),
    themeToggle: document.getElementById('themeToggle'),
    timeSeriesPanel: document.getElementById('timeSeriesPanel'),
    toast: document.getElementById('toast'),
    panels: [...document.querySelectorAll('[data-panel]')]
  };
}
