/**
 * Election results served from D1 (binding ELECTIONS_DB), mirroring the PRONI endpoints.
 *
 *   GET /_api/elections                                  -> { elections: [...] }  (index)
 *   GET /_api/elections?body=northern-ireland-assembly   -> filtered index
 *   GET /_api/elections?key=<key>                        -> one election + constituencies
 *   GET /_api/elections?key=<key>&constituency=<seq>     -> one constituency, candidates + counts
 *
 * Why this exists: the same data currently ships as 281 static JSON documents totalling
 * 322 MB, and the client downloads a whole 1-3 MB bundle to render a single election.
 * Worse, those documents are regenerated by `npm run build`, which Cloudflare Pages runs
 * at deploy time without the layer sources present, so most elections are rewritten with
 * matchedCount 0 on every deploy. Reading from D1 removes both problems: a query returns
 * kilobytes, and a deploy cannot rewrite the data because a deploy no longer writes it.
 *
 * The constituency -> feature match is a stored table rather than a build-time
 * computation, which is the specific change that retires that regression.
 */

const CACHE_VERSION = 'elections-1';

const ELECTION_COLS =
  'key, body, body_slug AS bodySlug, body_group AS bodyGroup, display_title AS displayTitle, '
  + 'contest_type AS contestType, kind, voting_system AS votingSystem, '
  + 'contest_status AS contestStatus, date, year, source_map_id AS sourceMapId, '
  + 'layer_id AS layerId, label_property AS labelProperty';

const CONS_COLS =
  'seq, name, winner_party AS winnerParty, winner_name AS winnerName, '
  + 'leading_party AS leadingParty, leading_name AS leadingName, leading_votes AS leadingVotes, '
  + 'leading_pct AS leadingPct, turnout_pct AS turnoutPct, majority, majority_pct AS majorityPct, '
  + 'seats_won AS seatsWon, seats_total AS seatsTotal, quota, electorate';

const CAND_COLS =
  'candidate_id AS id, name, party, party_id AS partyId, person_id AS personId, '
  + 'first_prefs AS firstPrefs, final_votes AS finalVotes, elected, elected_at AS electedAt, '
  + 'excluded, excluded_at AS excludedAt, status, colour, gender, meta';

/** meta holds every field not promoted to a column, so responses stay shape-compatible. */
function withMeta(row) {
  if (!row) return row;
  const { meta, ...rest } = row;
  if (!meta) return rest;
  try {
    return { ...rest, ...JSON.parse(meta) };
  } catch {
    return rest;
  }
}

export async function onRequestGet(context) {
  const cache = caches.default;
  const keyUrl = new URL(context.request.url);
  keyUrl.searchParams.set('_cv', CACHE_VERSION);
  const cacheKey = new Request(keyUrl.toString(), { method: 'GET' });
  const hit = await cache.match(cacheKey);
  if (hit) return hit;
  const resp = await handle(context);
  if (resp.status === 200) context.waitUntil(cache.put(cacheKey, resp.clone()));
  return resp;
}

async function handle(context) {
  const url = new URL(context.request.url);
  const key = (url.searchParams.get('key') || '').trim();
  const body = (url.searchParams.get('body') || '').trim();
  const constituency = url.searchParams.get('constituency');

  // Only successful responses are cacheable. Sending the long max-age on errors too
  // would have pinned a transient failure at the edge for up to a day -- a 503 from a
  // missing binding during a deploy, or a 500 from a bad query, would outlive its own
  // cause and look like a broken endpoint long after the fix shipped.
  const json = (payload, status = 200) => new Response(JSON.stringify(payload), {
    status,
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': status === 200
        ? 'public, max-age=3600, s-maxage=86400'
        : 'no-store',
      'Access-Control-Allow-Origin': '*',
    },
  });

  const db = context.env.ELECTIONS_DB;
  if (!db) return json({ error: 'ELECTIONS_DB binding not configured' }, 503);

  try {
    // Index: every election, or those for one body. Small enough to return whole.
    if (!key) {
      const stmt = body
        ? db.prepare(`SELECT ${ELECTION_COLS} FROM elections WHERE body_slug = ?1 ORDER BY date`).bind(body)
        : db.prepare(`SELECT ${ELECTION_COLS} FROM elections ORDER BY date`);
      const { results } = await stmt.all();
      return json({ elections: results || [], count: (results || []).length });
    }

    // One constituency, with its candidates and count rows.
    if (constituency !== null && constituency !== '') {
      const seq = Number(constituency);
      if (!Number.isInteger(seq)) return json({ error: 'constituency must be an integer' }, 400);
      const [cons, cands, counts, feature, anim] = await Promise.all([
        db.prepare(`SELECT ${CONS_COLS}, meta FROM constituencies WHERE election_key = ?1 AND seq = ?2`).bind(key, seq).first(),
        db.prepare(`SELECT ${CAND_COLS} FROM candidates WHERE election_key = ?1 AND constituency_seq = ?2 ORDER BY first_prefs DESC`).bind(key, seq).all(),
        db.prepare('SELECT candidate_id AS candidateId, count_number AS countNumber, total_votes AS totalVotes, transfers, status FROM counts WHERE election_key = ?1 AND constituency_seq = ?2 ORDER BY count_number, candidate_id').bind(key, seq).all(),
        db.prepare('SELECT layer_id AS layerId, feature_id AS featureId, feature_name AS featureName, match_name AS matchName, matched FROM constituency_features WHERE election_key = ?1 AND constituency_seq = ?2').bind(key, seq).first(),
        db.prepare('SELECT payload FROM constituency_animation WHERE election_key = ?1 AND constituency_seq = ?2').bind(key, seq).first(),
      ]);
      if (!cons) return json({ error: 'constituency not found' }, 404);
      // Stored verbatim and returned verbatim. The count-animation code consumes this
      // object directly, and its row shape varies across the corpus, so it is passed
      // through untouched rather than rebuilt from the counts table.
      let animationPayload = null;
      if (anim?.payload) {
        try {
          animationPayload = JSON.parse(anim.payload);
        } catch {
          animationPayload = null;
        }
      }
      return json({
        constituency: withMeta(cons),
        feature: feature || null,
        candidates: (cands.results || []).map(withMeta),
        counts: counts.results || [],
        animationPayload,
      });
    }

    // Bundle mode: assemble the exact shape of the static election bundle.
    //
    // This is the cutover path. The client's whole rendering stack consumes
    // bundle.results[], so serving that shape from D1 lets the source of truth move
    // without touching the renderer. It is deliberately NOT the efficient shape -- it
    // returns every constituency, so it is as large as the static file it replaces.
    // What it buys is correctness: this comes from D1, which a deploy cannot rewrite.
    // Serving one constituency at a time is a later change on the client side.
    if (url.searchParams.get('format') === 'bundle') {
      const [election, cons, cands, anims, feats] = await Promise.all([
        db.prepare(`SELECT ${ELECTION_COLS}, meta FROM elections WHERE key = ?1`).bind(key).first(),
        db.prepare(`SELECT ${CONS_COLS}, meta FROM constituencies WHERE election_key = ?1 ORDER BY seq`).bind(key).all(),
        db.prepare(`SELECT constituency_seq AS seq, ${CAND_COLS} FROM candidates WHERE election_key = ?1`).bind(key).all(),
        db.prepare('SELECT constituency_seq AS seq, payload FROM constituency_animation WHERE election_key = ?1').bind(key).all(),
        db.prepare('SELECT constituency_seq AS seq, feature_id AS featureId, feature_name AS featureName, match_name AS matchName, matched FROM constituency_features WHERE election_key = ?1').bind(key).all(),
      ]);
      if (!election) return json({ error: 'election not found' }, 404);

      const bySeq = (rows) => {
        const map = new Map();
        for (const row of rows.results || []) {
          if (!map.has(row.seq)) map.set(row.seq, []);
          map.get(row.seq).push(row);
        }
        return map;
      };
      const candBySeq = bySeq(cands);
      const animBySeq = new Map((anims.results || []).map((r) => [r.seq, r.payload]));
      const featBySeq = new Map((feats.results || []).map((r) => [r.seq, r]));

      const results = (cons.results || []).map((row) => {
        const { seq, name, ...rest } = withMeta(row);
        const candidates = (candBySeq.get(seq) || []).map((c) => {
          const { seq: _drop, ...candidate } = withMeta(c);
          return candidate;
        });
        let animationPayload = null;
        const raw = animBySeq.get(seq);
        if (raw) {
          try {
            animationPayload = JSON.parse(raw);
          } catch {
            animationPayload = null;
          }
        }
        const feature = featBySeq.get(seq) || {};
        return {
          constituency: name,
          ...rest,
          candidates,
          // Both derivable, and both omitted from storage for that reason: `elected` is
          // a subset of candidates, and countGroup is the animation payload's own rows.
          elected: candidates.filter((c) => c.elected),
          countGroup: animationPayload?.Constituency?.countGroup || [],
          animationPayload,
          featureId: feature.featureId ?? null,
          featureName: feature.featureName ?? null,
          matchName: feature.matchName ?? null,
          matched: feature.matched === 1,
        };
      });

      return json({
        ...withMeta(election),
        results,
        matchedCount: results.filter((r) => r.matched).length,
        unmatchedCount: results.filter((r) => !r.matched).length,
        loadable: results.length > 0 && results.some((r) => r.matched),
      });
    }

    // One election: header plus its constituencies and their feature matches.
    const [election, cons] = await Promise.all([
      db.prepare(`SELECT ${ELECTION_COLS}, meta FROM elections WHERE key = ?1`).bind(key).first(),
      db.prepare(
        `SELECT c.${CONS_COLS.split(', ').join(', c.')}, c.meta, `
        + 'f.feature_id AS featureId, f.feature_name AS featureName, f.matched '
        + 'FROM constituencies c '
        + 'LEFT JOIN constituency_features f '
        + '  ON f.election_key = c.election_key AND f.constituency_seq = c.seq '
        + 'WHERE c.election_key = ?1 ORDER BY c.seq'
      ).bind(key).all(),
    ]);
    if (!election) return json({ error: 'election not found' }, 404);
    const rows = (cons.results || []).map(withMeta);
    return json({
      election: withMeta(election),
      constituencies: rows,
      matchedCount: rows.filter((r) => r.matched).length,
      unmatchedCount: rows.filter((r) => !r.matched).length,
    });
  } catch (error) {
    return json({ error: String(error && error.message ? error.message : error) }, 500);
  }
}
