#!/usr/bin/env python3
"""Attach an `alignment_label` field to every candidacy in the test2 election metadata.

WHY HERE. The upstream source (election-viewer-package/data/elections/<body>/<date>/
<constituency>.json) is raw EONI-shaped count data: one row per candidate PER COUNT,
with no single object representing a candidacy. test/metadata/elections-test2/*.json is
the form in which each candidacy is exactly one object, and it is what the site and the
analysis both read, so that is where the field belongs.

Those files are generated by scripts/build-test2-election-manifest.mjs, which copies
candidates with an object spread ({...candidate, ...}), so `alignment_label` survives a
regeneration of the manifest. It does NOT survive a rebuild from upstream that discards
the existing files, so re-run this script after any such rebuild. It is idempotent.

VALUE. An ordered array of zero or more strings -- a tuple. An empty array means no rule
matched and no label has been set; it is written explicitly rather than left absent so
that "unlabelled" is distinguishable from "field not yet applied".

PRECEDENCE. An entry in alignment_overrides.csv wins over any party rule. That is the
mechanism for setting independents case-by-case, and for any party string this script
deliberately leaves alone.

Usage:
    python scripts/apply_alignment_labels.py            # apply
    python scripts/apply_alignment_labels.py --check    # report only, write nothing
"""
import os, sys, csv, json, glob, argparse, collections

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..'))
META = os.path.join(REPO, 'test', 'metadata', 'elections-test2')
ALIGN = os.path.join(REPO, 'data', 'elections', 'alignment')
RULES = os.path.join(ALIGN, 'alignment_rules.json')
OVERRIDES = os.path.join(ALIGN, 'alignment_overrides.csv')
FIELD = 'alignment_label'


def load_rules():
    with open(RULES, encoding='utf-8') as fh:
        spec = json.load(fh)
    compiled = []
    for r in spec['rules']:
        compiled.append({
            'id': r['id'],
            'labels': list(r['labels']),
            'strings': set(r['partyStrings']),
            'bodies': set(r['bodies']) if r.get('bodies') else None,
            'from': r.get('from'),
            'until': r.get('until'),
        })
    return spec, compiled


def load_overrides():
    """key -> labels. Key is electionKey|constituency|candidateId."""
    if not os.path.exists(OVERRIDES):
        return {}
    out = {}
    with open(OVERRIDES, encoding='utf-8-sig', newline='') as fh:
        for row in csv.DictReader(fh):
            key = (row.get('election_key') or '').strip()
            con = (row.get('constituency') or '').strip()
            cid = (row.get('candidate_id') or '').strip()
            if not key or not con:
                continue
            raw = (row.get('alignment_label') or '').strip()
            labels = [s.strip() for s in raw.split('|') if s.strip()] if raw else []
            out[f'{key}|{con}|{cid}'] = labels
    return out


def match(rules, party, body, date):
    for r in rules:
        if party not in r['strings']:
            continue
        if r['bodies'] is not None and body not in r['bodies']:
            continue
        if r['from'] and date < r['from']:
            continue
        if r['until'] and date >= r['until']:
            continue
        return r
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='report only; do not write any file')
    args = ap.parse_args()

    spec, rules = load_rules()
    overrides = load_overrides()
    vocab = set(spec['labelVocabulary'])
    bad = {l for r in rules for l in r['labels']} - vocab
    if bad:
        sys.exit(f'rule uses labels outside labelVocabulary: {sorted(bad)}')

    files = sorted(glob.glob(os.path.join(META, '*.json')))
    bodies_seen = set()
    labelled = collections.Counter()      # rule id -> n
    by_party = collections.Counter()      # party -> n candidacies
    party_labels = {}                     # party -> set of label-tuples applied
    unlabelled = collections.Counter()    # party -> n candidacies with no label
    unlab_body = collections.defaultdict(collections.Counter)
    ov_hits = 0
    changed_files = 0
    total = 0

    for path in files:
        with open(path, encoding='utf-8') as fh:
            doc = json.load(fh)
        key = doc.get('key') or os.path.basename(path)[:-5]
        body = doc.get('bodySlug') or os.path.basename(path).split('__')[0]
        date = str(doc.get('date') or os.path.basename(path).split('__')[1][:10])
        bodies_seen.add(body)
        dirty = False

        def resolve(cand, constituency):
            nonlocal ov_hits
            party = (cand.get('party') or '').strip()
            cid = str(cand.get('id') or '').strip()
            ok = f'{key}|{constituency}|{cid}'
            if ok in overrides:
                ov_hits += 1
                return list(overrides[ok]), 'override'
            r = match(rules, party, body, date)
            return (list(r['labels']), r['id']) if r else ([], None)

        for res in doc.get('results') or []:
            con = str(res.get('constituency') or '').strip()
            for cand in (res.get('candidates') or []):
                total += 1
                labels, src = resolve(cand, con)
                party = (cand.get('party') or '').strip()
                by_party[party] += 1
                if src:
                    labelled[src] += 1
                    party_labels.setdefault(party, set()).add(tuple(labels))
                else:
                    unlabelled[party] += 1
                    unlab_body[party][body] += 1
                if cand.get(FIELD) != labels:
                    cand[FIELD] = labels
                    dirty = True
                elif FIELD not in cand:
                    cand[FIELD] = labels
                    dirty = True

        # the top-level duplicate candidate list, where present, must agree
        for cand in (doc.get('mainLikeCandidateSummary') or []):
            con = str(cand.get('constituency') or '').strip()
            labels, _ = resolve(cand, con)
            if cand.get(FIELD) != labels:
                cand[FIELD] = labels
                dirty = True

        if dirty and not args.check:
            # Match the existing convention exactly -- 2-space indent, unescaped UTF-8,
            # LF endings, trailing newline -- so the diff is the inserted lines only and
            # not a 328 MB reformat of every file.
            with open(path, 'w', encoding='utf-8', newline='\n') as fh:
                json.dump(doc, fh, ensure_ascii=False, indent=2)
                fh.write('\n')
            changed_files += 1
        elif dirty:
            changed_files += 1

    # ---- validate that every `bodies` entry in the rules actually exists ----
    declared = {b for r in rules if r['bodies'] for b in r['bodies']}
    ghosts = declared - bodies_seen
    if ghosts:
        print(f"  WARNING: rules scope to bodySlug values not present in the data: "
              f"{sorted(ghosts)}")

    print("=" * 78)
    print(f"alignment_label — {total:,} candidacies across {len(files)} election files")
    print(f"  bodies present: {len(bodies_seen)}")
    print(f"\n  labelled by rule:")
    for r in rules:
        n = labelled.get(r['id'], 0)
        print(f"    {n:7,}  {r['id']:22} -> {r['labels']}")
    print(f"    {ov_hits:7,}  {'override':22} -> (per-candidacy, from alignment_overrides.csv)")
    tot_lab = sum(labelled.values()) + ov_hits
    print(f"\n  labelled {tot_lab:,} / {total:,} ({100*tot_lab/total:.1f}%)   "
          f"unlabelled {total-tot_lab:,} across {len(unlabelled)} distinct party strings")
    print(f"  files {'that would change' if args.check else 'written'}: {changed_files}")

    if args.check:
        print("\n  --check: nothing written")
        return

    # ---- review file: everything left unlabelled, biggest first ----
    os.makedirs(ALIGN, exist_ok=True)
    with open(os.path.join(ALIGN, 'alignment_review.csv'), 'w', encoding='utf-8',
              newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['party', 'candidacies', 'bodies', 'suggested_action'])
        for party, n in unlabelled.most_common():
            hint = ''
            low = party.lower()
            # Several 'Independent *' strings are registered parties in the Republic
            # (Independent Ireland, Independent Alliance, Independents 4 Change,
            # Independent Labour), not unaffiliated candidates, so they are called out
            # separately rather than sent to the per-candidacy override route.
            roi_ind_parties = {'independent ireland', 'independent alliance',
                               'independents 4 change', 'independent labour',
                               'independent health alliance',
                               'south kerry independent alliance'}
            if low in roi_ind_parties:
                hint = 'registered party in the Republic, not an unaffiliated candidate'
            elif low.startswith('independent') or low == 'independent':
                hint = 'independent — set per candidacy in alignment_overrides.csv'
            elif 'unionist' in low or 'loy' in low:
                hint = 'unionist-adjacent — not in the supplied list; confirm before labelling'
            elif 'sinn f' in low or 'republican' in low:
                hint = 'republican-adjacent but a distinct party from Sinn Féin'
            elif 'nationalist' in low:
                hint = 'nationalist-adjacent; check body and era'
            elif 'pbp' in low:
                hint = 'PBP-adjacent; separate registration from PBP'
            bodies = ','.join(f'{b}:{c}' for b, c in unlab_body[party].most_common())
            w.writerow([party, n, bodies, hint])

    # ---- coverage file: what each labelled string received ----
    with open(os.path.join(ALIGN, 'alignment_coverage.csv'), 'w', encoding='utf-8',
              newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['party', 'candidacies', 'distinct_label_tuples', 'labels'])
        for party in sorted(party_labels):
            tups = sorted(party_labels[party])
            w.writerow([party, by_party[party], len(tups),
                        ' ; '.join('|'.join(t) if t else '(none)' for t in tups)])

    print(f"\n  wrote data/elections/alignment/alignment_review.csv "
          f"({len(unlabelled)} unlabelled strings)")
    print(f"  wrote data/elections/alignment/alignment_coverage.csv "
          f"({len(party_labels)} labelled strings)")


if __name__ == '__main__':
    main()
