/**
 * Streaming CSV export of the records matching a PRONI search — same query
 * grammar and filters as /_api/proni/search. Generated by the site (not held on
 * the Internet Archive; that is what "Export all" is for). Rows are pulled from
 * D1 in pages and streamed, so memory stays bounded even for large result sets.
 *
 * Capped at MAX_ROWS to bound D1 work and file size; beyond that the app points
 * the user at "Export all".
 */
import { buildMatch, buildFilters } from './_query.js';

const MAX_ROWS = 50000;
const PAGE = 1000;
const COLS = 'p.ref, p.title, p.level, p.dates, p.access, p.digital_record, p.parent, '
  + 'ext.ext_display, ext.ext_start_year, ext.ext_end_year, ext.ext_circa, ext.ext_estimated, ext.ext_bound, ext.ext_undated, '
  + 'p.description';
const HEADER = ['PRONI Reference', 'Title', 'Level', 'Dates', 'Access', 'Digitised', 'Parent reference',
  'Extracted Dates', 'Extracted start year', 'Extracted end year', 'Approximate', 'Cataloguer-supplied', 'Open-ended bound', 'Undated',
  'Description'];

const csvCell = (v) => {
  const s = v == null ? '' : String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const csvRow = (arr) => arr.map(csvCell).join(',') + '\r\n';

export async function onRequestGet(context) {
  const url = new URL(context.request.url);
  const g = (k) => (url.searchParams.get(k) || '').trim();
  const q = g('q');
  const fields = { title: g('title'), description: g('description'), ref: g('ref'), text: g('text'), dates: g('dates') };
  const from = parseInt(g('from'), 10); const to = parseInt(g('to'), 10);

  const db = context.env.PRONI_DB;
  if (!db) return new Response('PRONI_DB binding not configured', { status: 503 });

  const match = buildMatch(q, fields);
  const { where, binds } = buildFilters({ letter: g('letter'), from, to, top: g('top') === '1', level: g('level'), access: g('access') });
  if (!match && !where.length) return new Response('Provide a search query or filter to export.', { status: 400 });

  let sql;
  if (match) {
    const w = where.length ? ' AND ' + where.join(' AND ') : '';
    sql = `SELECT ${COLS} FROM proni_fts f JOIN proni p ON p.rowid = f.rowid LEFT JOIN ext ON ext.ref = p.ref WHERE proni_fts MATCH ?${w} ORDER BY p.ref LIMIT ? OFFSET ?`;
  } else {
    sql = `SELECT ${COLS} FROM proni p LEFT JOIN ext ON ext.ref = p.ref WHERE ${where.join(' AND ')} ORDER BY p.ref LIMIT ? OFFSET ?`;
  }
  const head = match ? [match, ...binds] : binds;

  const enc = new TextEncoder();
  let offset = 0;
  let sent = 0;
  const stream = new ReadableStream({
    start(controller) { controller.enqueue(enc.encode('﻿' + csvRow(HEADER))); }, // BOM for Excel
    async pull(controller) {
      if (sent >= MAX_ROWS) { controller.close(); return; }
      const limit = Math.min(PAGE, MAX_ROWS - sent);
      let rows;
      try {
        const r = await db.prepare(sql).bind(...head, limit, offset).all();
        rows = r.results || [];
      } catch (e) {
        controller.enqueue(enc.encode(csvRow([`ERROR: ${e && e.message || e}`])));
        controller.close();
        return;
      }
      for (const r of rows) {
        controller.enqueue(enc.encode(csvRow([
          r.ref, r.title, r.level, r.dates, r.access,
          r.digital_record ? 'Yes' : '', r.parent,
          r.ext_display, r.ext_start_year, r.ext_end_year,
          r.ext_circa ? 'Yes' : '', r.ext_estimated ? 'Yes' : '', r.ext_bound || '', r.ext_undated ? 'Yes' : '',
          r.description,
        ])));
      }
      sent += rows.length;
      offset += rows.length;
      if (rows.length < limit) controller.close();
    },
  });

  const stamp = (q || g('letter') || 'all').replace(/[^a-zA-Z0-9]+/g, '-').slice(0, 40).replace(/^-|-$/g, '') || 'results';
  return new Response(stream, {
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="proni-search-${stamp}.csv"`,
      'Cache-Control': 'no-store',
    },
  });
}
